stages:
  - test
  - release

before_script:
  - virtualenv env
  - source env/bin/activate
  - pip install -U pip wheel setuptools

test:
  image:
    name: eventyay-tickets/ci-image
  stage: test
  script:
    - XDG_CACHE_HOME=/cache pip install -e ".[dev]"
    - cd src
    - python manage.py check
    - make all compress
    - pytest --reruns 3 -n 3 tests
  tags:
    - python3
  except:
    - pypi

style:
  image:
    name: eventyay-tickets/ci-image
  stage: test
  script:
    - pip install -U isort black flake8 check-manifest
    - isort -c --gitignore .
    - black --check .
    - flake8 --extend-exclude .cache .
    - check-manifest --ignore .cache .
  tags:
    - python3
  except:
    - pypi

pypi:
  image:
    name: eventyay-tickets/ci-image
  stage: release
  before_script:
    - cp /keys/.pypirc ~/.pypirc
  script:
    - pip install -U check-manifest twine
    - XDG_CACHE_HOME=/cache pip install -e ".[dev]"
    - cd src
    - python setup.py sdist
    - pip install dist/pretix-*.tar.gz
    - python -m pretix migrate
    - python -m pretix check
    - check-manifest
    - make npminstall
    - python setup.py sdist bdist_wheel
    - twine check dist/*
    - twine upload dist/*
  tags:
    - python3
  only:
    - pypi
  artifacts:
    paths:
      - src/dist/
