# Generated by Django 5.2.5 on 2026-01-19 17:22

import django.db.models.deletion
import exhibitors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0006_remove_landing_page_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=exhibitors.models.exhibitor_logo_path)),
                ('key', models.CharField(default=exhibitors.models.generate_key, max_length=8)),
                ('booth_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('booth_name', models.CharField(max_length=100, verbose_name='BoothName')),
                ('lead_scanning_enabled', models.BooleanField(default=False)),
                ('allow_voucher_access', models.BooleanField(default=False)),
                ('allow_lead_access', models.BooleanField(default=False)),
                ('lead_scanning_scope_by_device', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.event')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibitor_name', models.CharField(max_length=190)),
                ('pseudonymization_id', models.CharField(max_length=190)),
                ('scanned', models.DateTimeField()),
                ('scan_type', models.CharField(max_length=50)),
                ('device_name', models.CharField(max_length=50)),
                ('attendee', models.JSONField(blank=True, null=True)),
                ('booth_id', models.CharField(max_length=100)),
                ('booth_name', models.CharField(max_length=100, verbose_name='BoothName')),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibitors.exhibitorinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibitors_access_mail_subject', models.CharField(max_length=255)),
                ('exhibitors_access_mail_body', models.TextField()),
                ('allowed_fields', models.JSONField(default=list)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.event')),
            ],
            options={
                'unique_together': {('event',)},
            },
        ),
        migrations.CreateModel(
            name='ExhibitorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='exhibitors.exhibitorinfo')),
            ],
            options={
                'ordering': ['-use_count', 'name'],
                'unique_together': {('exhibitor', 'name')},
            },
        ),
    ]
