# Generated by Django 5.2.10 on 2026-01-21 08:35

import i18nfield.fields
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_event_locale_alter_question_hidden_and_more'),
        ('exhibitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitorinfo',
            name='booth_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitorinfo',
            name='booth_name',
            field=i18nfield.fields.I18nCharField(max_length=100, verbose_name='Booth Name'),
        ),
        migrations.AlterField(
            model_name='exhibitorinfo',
            name='description',
            field=i18nfield.fields.I18nTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='exhibitorinfo',
            name='name',
            field=i18nfield.fields.I18nCharField(max_length=190, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='booth_name',
            field=models.CharField(max_length=100, verbose_name='Booth Name'),
        ),
        migrations.AddConstraint(
            model_name='exhibitorinfo',
            constraint=models.UniqueConstraint(
                fields=('event', 'booth_id'),
                condition=Q(booth_id__isnull=False),
                name='exhibitorinfo_event_booth_id_uniq',
            ),
        ),
    ]
